name: fetch SEO data
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checout
        uses: actions/checkout@v2

      - name: module install
        run: npm install

      - name: Build book
        run: npm run gen-link

      - name: Deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync --region ap-northeast-1 dist/metadata/ s3://blog.sasakiy84.net/metadata
